[tool.isort]
atomic = true
combine_star = true
ensure_newline_before_comments = true
force_grid_wrap = 0
include_trailing_comma = true
indent = 4
known_django = "django"
known_first_party = "common,meta"
line_length = 119
profile = "black"
multi_line_output = 5
sections = "FUTURE,STDLIB,THIRDPARTY,DJANGO,FIRSTPARTY,LOCALFOLDER"
skip_gitignore = true
use_parentheses = true

[tool.black]
exclude = '''
(
    /(
        \.git
        | \.github
        | \.venv
        | __pycache__
    )/
)
'''
line-length = 119
target-version = ["py39"]
